### ISSUE TITLE
I can't access to the .html file for UI automation testing

### ISSUE THREAD

**Issue by andersonhurtado** [NeutroniumCore/Neutronium#107]
I have been trying automated some Vue examples from your repository with robot framework and selenium for C# but I couldn't access to the .html file

Could you any idea to access the file?

**Comment by David-Desmaisons** [comment]
Could you explain what do you kind of test you intend to do? It is not very clear for me what kind of tests you intend to perform.
I am not sure about what do you mean by access by html files either.
Neutronium build will generate html file that cannot be opened directly in the browser since some bindings are injected in the embeded broswer.
Since C# integration is not using http protcol there is no way you could process integrated test only in the browser,

**Comment by andersonhurtado** [comment]
Hello David,

Thanks for your time, well, I try to develop automated UI tests with the C# Selenium library 

I know the HTML file is embedded but is there an option to access it? because the actions come from it

I tried to access this URI "pack://application:,,,/src/index.html" but visual studio stopped on one .dll file at the end in the test without error

Regards,

A. H.

**Comment by David-Desmaisons** [comment]
I am still missing the big picture.
Do you intend to perform integration tests, including C# code?

If so trying to open the generated html won't be enougth: it is not because the HTML is embedded but because Neutronium browser autamically inject bindings and scripts to the HTML files. Without these injection, the page will bebrokrn.

**Comment by andersonhurtado** [comment]
Hello David,

I don't try to do performance tests, I've been trying to develop UI tests with this sample code "Example.ChromiumFX.Vue.UI.exe"

I just need to open, interact with HTML components, interact with WPF components and close the .exe file

It isn't unit testing, it's automated functional testing with a final version so I suppose that "Example.ChromiumFX.Vue.UI.exe" should work, do not?

Regards,

A. H.

**Comment by David-Desmaisons** [comment]
Well, as stated before:
Opening HTML files in a standalone browser is useless.
>  Neutronium browser automatically inject bindings and scripts to the HTML files. Without these injection, the page will be broken.

So selenium is not an option.

**Comment by andersonhurtado** [comment]
Hello David,

Thank you for your time. I'll found another way to test.

Regards,

A. H.
