### ISSUE TITLE
custom schema for assets not in the packed file

### ISSUE THREAD

**Issue by agnauck** [NeutroniumCore/Neutronium#38]
Is is possible to register custom schemas over ChromiumFx so that files not in the pack resource can be served?
Eg images stored in the users profile directory.

**Comment by David-Desmaisons** [comment]
@agnauck , currently Neutronium supports out-of-the-box loading the following files from your csproject:
1) Files with Build Action: Resource, Copy: None
2) Files with Build Action: Content. Copy: Always

File available on the file system should be loaded without problem.

If you need something more, it also possible to provide a custom `CfxResourceHandler`, see an implmentation [here](https://github.com/NeutroniumCore/Neutronium/blob/master/WebBrowserEngine/ChromiumFX/HTMEngine.ChromiumFX/WPF/PackUriResourceHandler.c).
To register it, you need to get a reference to `IWPFCfxWebWindow`  in order to access the underlying ChromiumFx [ChromiumWebBrowser](https://bitbucket.org/chromiumfx/chromiumfx/src/25c83dc7ef6f204e85645725bf27fdfcd639e176/ChromiumWebBrowser/ChromiumWebBrowser.cs?at=default&fileviewer=file-view-default). 

See [Example.ChromiumFX.Vue.SOP](https://github.com/NeutroniumCore/Neutronium/blob/4589e86c2bb93c30dc62a2b5c8bcca388242b4c6/Examples/Example.ChromiumFX.Vue.SOP/MainWindow.xaml.cs) main window as an example how to get a reference to IWPFCfxWebWindow

**Comment by agnauck** [comment]
thanks, this is exactly what I was looking for.
I am working on a prototype, the c# backend will download some assets like images in the background and put them somewhere in the user profile directy. They will be diplayed in the frontend then. This is why I can't include them as a resource, there will be dynamic.

**Comment by David-Desmaisons** [comment]
Ok, got you. The only "Gotcha" you should be aware of is that you need to hold a reference to the corresponding CfxResourceHandler during the lifetime of the Wpf control to avoid bug.

**Comment by simonbuehler** [comment]
Sorry for using this old issue - I have the exact same requirements and there was a file based resource handler which also set the correct mime type for local js files so the module loader did load them, but I can't find it anymore in the sources , 

Any hint or do you have a working implementation still around?
