### ISSUE TITLE
DebugTools-Toolbar missing

### ISSUE THREAD

**Issue by genyx** [NeutroniumCore/Neutronium#72]
I don't have the DebugTools Toolbar anymore. However when i rightclick in the Chromium i can still open the VM and Chrome-Inspector as usual. Just the Toolbar is missing.

I am in Debug Mode and the folder "DebugTools" is definitely in the right location.

I suggest the problem has to do with the following:

I splitted my application apart in multiple projects, having one project with the App.xaml (which is the ChromiumFxWebBrowserApp) and this is the entry point assembly. One other project in my solution is for all GUI related stuff, containing the MainWindow.xaml and more.

The application is working fine, just the toolbar is missing. How can this come?

**Comment by jmecosta** [comment]
Right click on the ui :)

**Comment by jmecosta** [comment]
Ups you know that

**Comment by David-Desmaisons** [comment]
Hello @genyx , The debug tools has been  removed on purpose: since the commands have been added to the contextual menu in version 1.2.0, there were no more need to have the debugtools.
By itself, It was problematic for two  reason:
-When the window was very small,the layout was broken.
-It prevents to have an 100% acurrate view of the layout in debug mode since the debug toolbar was at the bottom of the Neutronium control. That meant that real layout could be only seen in none-debug condition, and that could pretty anoying when it comes to adjust full screen layout.
