### ISSUE TITLE
Are there any specific things that Neutronium is NOT able to do?

### ISSUE THREAD

**Issue by MostHated** [NeutroniumCore/Neutronium#91]
Hey there,
    I came across this and thought it looked pretty interesting. I looked over the FAQ and things of that nature but I was wondering if there happened to be a list of things that Neutronium simply isn't able to do or replace when compared to something standard like WPF or even a typical website? Possibly just some info on things in which it just might not be best suited to use. I am fairly new to the whole Desktop ecosystem, so I am trying to research as much as I can to figure out what works best for me. I just started using Caliburn.Micro as well, which I really like, so I was wondering if it is known to be able to work with that as well? I know it mentioned a few frameworks, but don't recall if it said "All" of them.

Thanks!
-MH

**Comment by David-Desmaisons** [comment]
Hi @MostHated , in terms of binding, Neutronium provides the full range of WPF API including command and collections.
Since version 1.3.0 chromelless windows are fully supported, so it is possible 
Regarding templating, if you consider the vue binding for example the solution provided is powerful and by a degree simplier than WPF. Live reload would provide also a productivity bounce.
For a good demo of Neutronium possibility you can take a look at the Neutronium version of [ReactiveTrader](https://github.com/David-Desmaisons/ReactiveTrader), it is a good example on how it is possible to write a different view layer on the top of view model inicially designed for WPF. It demostrate also the performace of the solution for very fast changing data.
Maybe Neutronium can be considered overkilled if you aim a very simple UI but I have no scenario in mind where I would  consider it as not well suited.

**Comment by MostHated** [comment]
Thank you for the reply, I very much appreciate it. What version of HTML does it actually use, is it HTML5? I am not wanting an extremely crazy UI, but I would like to have some slight transition and menu item switching animation. Subtle things like a slight slide here, or a fade there. I was currently attempting to use Mahapps with Caliburn, I just started using it the other day, but I already hate wpf/xaml, lol.

**Comment by David-Desmaisons** [comment]
Well this is HTML5, chromium version 58 and more for the current version.
I would say that having a good understanding of modern Web technology and tools such as Webpack would be a big plus before starting developing a Neutronium
